pod 'AFNetworking'
pod 'SVProgressHUD', '~> 1.1.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'JSONModel', '~> 1.0.2'
pod 'Masonry'
pod 'HexColors'
pod 'ELCImagePickerController'
pod 'FMDB'
pod 'TPKeyboardAvoiding', '~> 1.2.4'